apiVersion: v1
kind: Service
metadata:
  name: blog-fe
  namespace: blog
  labels:
    app.kubernetes.io/name: blog-fe
    app.kubernetes.io/part-of: blog
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: blog-fe
  ports:
    - name: http
      port: 3000
      targetPort: http
      protocol: TCP
